@ContosoPizza_HostAddress = http://localhost:5201

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###

<!-- Send Request: returns a list of all pizzas in JSON -->

HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
Date: Wed, 17 Jan 2024 16:57:09 GMT
Server: Kestrel
Transfer-Encoding: chunked

[
    {
        "id": 1,
        "name": "Classic Italian",
        "isGlutenFree": false
    },
    {
        "id": 2,
        "name": "Veggie",
        "isGlutenFree": true
    }
]

<!-- GET request -->
GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Fri, 02 Apr 2021 21:57:57 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
    "id": 1,
    "name": "Classic Italian",
    "isGlutenFree": false
}

GET {{ContosoPizza_HostAddress}}/pizza/1
Accept: application/json

###

<!-- returns 404 Not Found -->

HTTP/1.1 404 Not Found
Content-Type: application/problem+json; charset=utf-8
Date: Fri, 02 Apr 2021 22:03:06 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    "traceId": "00-ec263e401ec554b6a2f3e216a1d1fac5-4b40b8023d56762c-00"
}

GET {{ContosoPizza_HostAddress}}/pizza/5
Accept: application/json

###